export const  SET_USER_INFO = 'SET_USER_INFO';
export const ADD_DRINK_TO_BOARD = 'ADD_DRINK';
export const REFRESH_DRINKS_IN_BOARD = 'REFRESH_DRINKS_IN_BOARD'
export const ADD_SEARCH_RESULTS = 'ADD_SEARCH_RESULTS';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
