export const  SET_USER_INFO = "SET_USER_INFO";
export const ADD_DRINK_TO_BOARD = "ADD_DRINK";
export const ADD_DRINK_TO_DISPLAY = "ADD_DRINK_TO_DISPLAY";
export const CLEAR_ACTUALLY_DIPLAYING_DRINK = "CLEAR_ACTUALLY_DISPLAYING_DRINK";
